version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      docusaurus:
        patterns:
          - '@docusaurus/*'
          - '@mdx-js/*'
          - react
          - react-dom

  - package-ecosystem: gomod
    directory: /examples/frameworks
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
